version: "3.3"
services:
  mongo:
    image : mongo:4.4.3
    container_name: project_name-mongo
    ports:
      - 127.0.0.1:27017:27017
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./database:/data/db
    restart: unless-stopped

  redis:
    image : redis
    container_name: project_name-redis
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis:/data

  rabbitmq:
    hostname: 'project_name-rabbitmq'
    image: rabbitmq:3.5-management
    container_name: 'project_name-rabbitmq'
    expose:
      - "5672"
      - "15672"
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    volumes:
      - ./rabbitmq/logs:/var/log/rabbitmq
      - ./rabbitmq/data:/var/lib/rabbitmq

  server:
    env_file:
      - .env.docker
    environment:
      - REDIS_URL=redis://redis
      - RABBITMQ_URL=amqp://rabbitmq
      - DB_CONNECTION_STRING=mongodb://mongo/db_name
    volumes:
      - ./exports:/app/exports
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: unless-stopped
    command: node dist/index.js
